/** Field labels the browser tools treat as a secret's, and ordinary ones beside them. */
/** Labels a field for a secret is known by, beyond passwords and codes, one per kind. */
export const SECRET_LABELS = [
  'SSN',
  'Social Security number',
  'National ID number',
  'National insurance number',
  'Tax ID',
  'Taxpayer identification number',
  'ITIN',
  'Security question',
  'Answer to your security question',
  'Secret answer',
  "Mother's maiden name",
  'Card number',
  'Credit card',
  'Debit card number',
  'Expiry date',
  'Expiration date',
  'MM/YY',
  'CVV',
  'CVV2',
  'CSC',
  'Account number',
  'Bank account',
  'Routing number',
  'ABA',
  'IBAN',
  'Sort code',
  'Backup codes',
  'Recovery codes',
  'Authenticator code',
] as const;

/** An ordinary form's labels, some sharing a word with a secret's. */
export const ORDINARY_LABELS = [
  'Name',
  'Email',
  'Phone',
  'Street address',
  'City',
  'ZIP code',
  'Promo code',
  'Order number',
  'Tracking number',
  'Company',
  'Account name',
  'Card holder',
  'Date of birth',
  'Message',
] as const;
